CREATE TABLE animals(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(250),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BIT,
	weight_kg DECIMAL,
	PRIMARY KEY( id )
);

--Add a column species of type string to your animals table.
ALTER TABLE animals ADD species CHAR(250);

--query multiple tables

--create ownerS table 
CREATE TABLE owners(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	full_name CHAR(255),
	age INT,
	PRIMARY KEY( id )
);

-- create species table
CREATE TABLE species(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(255),
	PRIMARY KEY( id )
);

--Modify animals table

-- Remove column species
ALTER TABLE animals DROP COLUMN species;

--Add column species_id which is a foreign key referencing species table
ALTER TABLE animals ADD species_id INT;

ALTER TABLE animals
ADD CONSTRAINT s_id 
FOREIGN KEY (species_id) 
REFERENCES species(id);

--Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals ADD owner_id INT;

ALTER TABLE animals
ADD CONSTRAINT o_id 
FOREIGN KEY (owner_id) 
REFERENCES owners (id);
