CREATE TABLE animals(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(250),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BIT,
	weight_kg DECIMAL,
	PRIMARY KEY( id )
);

--Add a column species of type string to your animals table.
ALTER TABLE animals ADD species CHAR(250);