CREATE TABLE animals(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(250),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BIT,
	weight_kg DECIMAL,
	PRIMARY KEY( id )
);

--Add a column species of type string to your animals table.
ALTER TABLE animals ADD species CHAR(250);

--query multiple tables

--create ownerS table 
CREATE TABLE owners(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	full_name CHAR(255),
	age INT,
	PRIMARY KEY( id )
);

-- create species table
CREATE TABLE species(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(255),
	PRIMARY KEY( id )
);

--Modify animals table

-- Remove column species
ALTER TABLE animals DROP COLUMN species;

--Add column species_id which is a foreign key referencing species table
ALTER TABLE animals ADD species_id INT;

ALTER TABLE animals
ADD CONSTRAINT s_id 
FOREIGN KEY (species_id) 
REFERENCES species(id);

--Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals ADD owner_id INT;

ALTER TABLE animals
ADD CONSTRAINT o_id 
FOREIGN KEY (owner_id) 
REFERENCES owners (id);

--add "join table" for visits

--Create a table named vets

CREATE TABLE vets(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name CHAR(255),
	age INT,
	date_of_graduation DATE,
	PRIMARY KEY( id )
);

-- Create a "join table" called specializations

CREATE TABLE specializations(
	species_id INT,
	vet_id INT
);

--Create a "join table" called visits
 CREATE TABLE visits(
	 animal_id INT,
	 vet_id INT,
	 v_date DATE
 );

 -- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

--create an index for visits
CREATE INDEX vet_ids_asc ON visits(vet_id ASC);

--create owners email index
CREATE INDEX owners_emails_asc ON owners(email ASC);